version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - JWT_SECRET=secret
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo
    ports:
      - "27017:27017"
